[project]
name = "last-war-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.0.0",
    "pandas<3.0.0",
    "pendulum>=3.1.0",
    "pytest>=9.0.2",
    "streamlit>=1.40.0",
]
